version: "3.8"

services:
  db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_INITDB_SKIP_TZINFO: thisisfine
      MYSQL_DATABASE: excity

  backend:
    depends_on:
      - db
    build: .
    restart: on-failure
    container_name: excity
    ports:
      - "8080:8080"
    environment:
      MYSQL_DB_HOST: jdbc:mysql://db
      MYSQL_DB_PORT: 3306
    command: ./start.sh